{{- if not .Values.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reshapr-ctrl-plane.fullname" . }}-admin-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reshapr-ctrl-plane.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.admin.nameKey }}: {{ .Values.admin.nameValue | b64enc | quote }}
  {{ .Values.admin.passwordKey }}: {{ .Values.admin.passwordValue | b64enc | quote }}
  {{ .Values.admin.emailKey }}: {{ .Values.admin.emailValue | b64enc | quote }}
  {{ .Values.admin.defaultGatewayTokensKey }}: {{ .Values.admin.defaultGatewayTokensValue | b64enc | quote }}
{{- end }}
